-- MySQL Script generated by MySQL Workbench
-- mié 23 sep 2020 15:51:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema productos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `productos` ;

-- -----------------------------------------------------
-- Schema productos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productos` DEFAULT CHARACTER SET utf8 ;
USE `productos` ;

-- -----------------------------------------------------
-- Table `productos`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos`.`productos` ;

CREATE TABLE IF NOT EXISTS `productos`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `sku` VARCHAR(14) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO productos.producto
(codigo, sku, descripcion, created_at, updated_at)
VALUES(1234, 'SN171800042539', "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", CURRENT_TIMESTAMP(), NULL),
(1235, 'SN171800042531', "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent venenatis est nec nisl rhoncus dignissim. Phasellus sit amet nibh mauris. Phasellus euismod, urna eget lobortis dapibus, sapien lectus varius sem, eu ornare nunc nibh a ipsum. Integer euismod eget dolor quis sagittis. Proin eleifend nisl ac sapien placerat, consequat hendrerit risus egestas. Ut ultrices tempus tellus, quis consequat velit lacinia a.", CURRENT_TIMESTAMP(), NULL),
(1236, 'SN171800042532', "Sed efficitur magna nec accumsan porta. Phasellus non urna nulla. Nullam dapibus mauris elit, quis volutpat diam euismod faucibus. Fusce quis sem sit amet dolor tempus bibendum. Aliquam ornare risus quis tellus tempor, ut porta turpis rhoncus. Vestibulum mattis leo risus, a cursus quam condimentum a. Nam euismod elit vel orci dignissim, ac blandit mi lobortis. Pellentesque aliquam felis sit amet eros hendrerit condimentum. Aenean vestibulum mi ac turpis rutrum hendrerit. Sed malesuada dictum enim non tempus. Sed at orci placerat, sollicitudin ex nec, pretium arcu. In quis bibendum neque.", CURRENT_TIMESTAMP(), NULL),
(4321, 'SN171800012345', "Nam nisl enim, sagittis id lorem id, pharetra varius ligula. Pellentesque placerat velit ac justo blandit, vel consectetur risus imperdiet. In vestibulum dolor ac maximus auctor. Suspendisse tristique nulla ac blandit congue. Nunc eget sollicitudin nisi, quis dictum sem. Fusce pellentesque ex ac velit consectetur dictum. Morbi ornare nisi non velit egestas auctor sit amet ac nibh. Curabitur eu porta turpis. Sed ac libero elit. Pellentesque sed augue tellus. Pellentesque quis ullamcorper magna, nec aliquam erat.", CURRENT_TIMESTAMP(), NULL),
(4326, 'SN171800012346', "Phasellus suscipit ligula eget dapibus eleifend. Quisque ac maximus purus. Aliquam risus arcu, fermentum et urna id, posuere varius nibh. Vivamus ut ex lacinia, convallis tortor vitae, pellentesque felis. In dolor ligula, mattis sed condimentum a, tempus quis nisl. In sit amet lorem lacinia, ultricies eros feugiat, varius nunc. Praesent ut facilisis nisl, nec fringilla justo. Duis semper ac libero vel faucibus. Etiam fringilla massa sit amet magna bibendum, viverra tincidunt felis euismod. Donec elit sapien, mattis id mauris sit amet, aliquet eleifend purus. Nam rutrum erat nec odio faucibus lobortis. Nam venenatis vitae turpis quis tristique. Cras sollicitudin sagittis leo eget imperdiet. Aenean nec quam eget sapien eleifend elementum.", CURRENT_TIMESTAMP(), NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
